/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as DeUeberRouteImport } from './routes/de/ueber'
import { Route as DeTeamRouteImport } from './routes/de/team'
import { Route as DeSpendenRouteImport } from './routes/de/spenden'
import { Route as DeKurseRouteImport } from './routes/de/kurse'
import { Route as DeKontaktRouteImport } from './routes/de/kontakt'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as DeProjekteIndexRouteImport } from './routes/de/projekte/index'
import { Route as AdminTeamMembersIndexRouteImport } from './routes/admin/team-members/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminBlogPostsIndexRouteImport } from './routes/admin/blog-posts/index'
import { Route as DeProjekteSlugRouteImport } from './routes/de/projekte/$slug'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminTeamMembersIdRouteImport } from './routes/admin/team-members/$id'
import { Route as AdminProjectsIdRouteImport } from './routes/admin/projects/$id'
import { Route as AdminPagesSlugRouteImport } from './routes/admin/pages/$slug'
import { Route as AdminCoursesIdRouteImport } from './routes/admin/courses/$id'
import { Route as AdminBlogPostsIdRouteImport } from './routes/admin/blog-posts/$id'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeUeberRoute = DeUeberRouteImport.update({
  id: '/de/ueber',
  path: '/de/ueber',
  getParentRoute: () => rootRouteImport,
} as any)
const DeTeamRoute = DeTeamRouteImport.update({
  id: '/de/team',
  path: '/de/team',
  getParentRoute: () => rootRouteImport,
} as any)
const DeSpendenRoute = DeSpendenRouteImport.update({
  id: '/de/spenden',
  path: '/de/spenden',
  getParentRoute: () => rootRouteImport,
} as any)
const DeKurseRoute = DeKurseRouteImport.update({
  id: '/de/kurse',
  path: '/de/kurse',
  getParentRoute: () => rootRouteImport,
} as any)
const DeKontaktRoute = DeKontaktRouteImport.update({
  id: '/de/kontakt',
  path: '/de/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeProjekteIndexRoute = DeProjekteIndexRouteImport.update({
  id: '/de/projekte/',
  path: '/de/projekte/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamMembersIndexRoute = AdminTeamMembersIndexRouteImport.update({
  id: '/admin/team-members/',
  path: '/admin/team-members/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/admin/pages/',
  path: '/admin/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/admin/courses/',
  path: '/admin/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogPostsIndexRoute = AdminBlogPostsIndexRouteImport.update({
  id: '/admin/blog-posts/',
  path: '/admin/blog-posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeProjekteSlugRoute = DeProjekteSlugRouteImport.update({
  id: '/de/projekte/$slug',
  path: '/de/projekte/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamMembersIdRoute = AdminTeamMembersIdRouteImport.update({
  id: '/admin/team-members/$id',
  path: '/admin/team-members/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIdRoute = AdminProjectsIdRouteImport.update({
  id: '/admin/projects/$id',
  path: '/admin/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesSlugRoute = AdminPagesSlugRouteImport.update({
  id: '/admin/pages/$slug',
  path: '/admin/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIdRoute = AdminCoursesIdRouteImport.update({
  id: '/admin/courses/$id',
  path: '/admin/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogPostsIdRoute = AdminBlogPostsIdRouteImport.update({
  id: '/admin/blog-posts/$id',
  path: '/admin/blog-posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/donate': typeof DonateRoute
  '/imprint': typeof ImprintRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/de/kontakt': typeof DeKontaktRoute
  '/de/kurse': typeof DeKurseRoute
  '/de/spenden': typeof DeSpendenRoute
  '/de/team': typeof DeTeamRoute
  '/de/ueber': typeof DeUeberRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/blog-posts/$id': typeof AdminBlogPostsIdRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/team-members/$id': typeof AdminTeamMembersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/de/projekte/$slug': typeof DeProjekteSlugRoute
  '/admin/blog-posts': typeof AdminBlogPostsIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/team-members': typeof AdminTeamMembersIndexRoute
  '/de/projekte': typeof DeProjekteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/donate': typeof DonateRoute
  '/imprint': typeof ImprintRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/de/kontakt': typeof DeKontaktRoute
  '/de/kurse': typeof DeKurseRoute
  '/de/spenden': typeof DeSpendenRoute
  '/de/team': typeof DeTeamRoute
  '/de/ueber': typeof DeUeberRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/blog-posts/$id': typeof AdminBlogPostsIdRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/team-members/$id': typeof AdminTeamMembersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/de/projekte/$slug': typeof DeProjekteSlugRoute
  '/admin/blog-posts': typeof AdminBlogPostsIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/team-members': typeof AdminTeamMembersIndexRoute
  '/de/projekte': typeof DeProjekteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/donate': typeof DonateRoute
  '/imprint': typeof ImprintRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/de/kontakt': typeof DeKontaktRoute
  '/de/kurse': typeof DeKurseRoute
  '/de/spenden': typeof DeSpendenRoute
  '/de/team': typeof DeTeamRoute
  '/de/ueber': typeof DeUeberRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/blog-posts/$id': typeof AdminBlogPostsIdRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/team-members/$id': typeof AdminTeamMembersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/de/projekte/$slug': typeof DeProjekteSlugRoute
  '/admin/blog-posts/': typeof AdminBlogPostsIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/team-members/': typeof AdminTeamMembersIndexRoute
  '/de/projekte/': typeof DeProjekteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/donate'
    | '/imprint'
    | '/privacy-policy'
    | '/team'
    | '/admin/login'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/users'
    | '/de/kontakt'
    | '/de/kurse'
    | '/de/spenden'
    | '/de/team'
    | '/de/ueber'
    | '/projects/$slug'
    | '/admin'
    | '/projects'
    | '/admin/blog-posts/$id'
    | '/admin/courses/$id'
    | '/admin/pages/$slug'
    | '/admin/projects/$id'
    | '/admin/team-members/$id'
    | '/api/auth/$'
    | '/api/media/$'
    | '/de/projekte/$slug'
    | '/admin/blog-posts'
    | '/admin/courses'
    | '/admin/pages'
    | '/admin/projects'
    | '/admin/team-members'
    | '/de/projekte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/donate'
    | '/imprint'
    | '/privacy-policy'
    | '/team'
    | '/admin/login'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/users'
    | '/de/kontakt'
    | '/de/kurse'
    | '/de/spenden'
    | '/de/team'
    | '/de/ueber'
    | '/projects/$slug'
    | '/admin'
    | '/projects'
    | '/admin/blog-posts/$id'
    | '/admin/courses/$id'
    | '/admin/pages/$slug'
    | '/admin/projects/$id'
    | '/admin/team-members/$id'
    | '/api/auth/$'
    | '/api/media/$'
    | '/de/projekte/$slug'
    | '/admin/blog-posts'
    | '/admin/courses'
    | '/admin/pages'
    | '/admin/projects'
    | '/admin/team-members'
    | '/de/projekte'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/donate'
    | '/imprint'
    | '/privacy-policy'
    | '/team'
    | '/admin/login'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/users'
    | '/de/kontakt'
    | '/de/kurse'
    | '/de/spenden'
    | '/de/team'
    | '/de/ueber'
    | '/projects/$slug'
    | '/admin/'
    | '/projects/'
    | '/admin/blog-posts/$id'
    | '/admin/courses/$id'
    | '/admin/pages/$slug'
    | '/admin/projects/$id'
    | '/admin/team-members/$id'
    | '/api/auth/$'
    | '/api/media/$'
    | '/de/projekte/$slug'
    | '/admin/blog-posts/'
    | '/admin/courses/'
    | '/admin/pages/'
    | '/admin/projects/'
    | '/admin/team-members/'
    | '/de/projekte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DonateRoute: typeof DonateRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TeamRoute: typeof TeamRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DeKontaktRoute: typeof DeKontaktRoute
  DeKurseRoute: typeof DeKurseRoute
  DeSpendenRoute: typeof DeSpendenRoute
  DeTeamRoute: typeof DeTeamRoute
  DeUeberRoute: typeof DeUeberRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  AdminBlogPostsIdRoute: typeof AdminBlogPostsIdRoute
  AdminCoursesIdRoute: typeof AdminCoursesIdRoute
  AdminPagesSlugRoute: typeof AdminPagesSlugRoute
  AdminProjectsIdRoute: typeof AdminProjectsIdRoute
  AdminTeamMembersIdRoute: typeof AdminTeamMembersIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
  DeProjekteSlugRoute: typeof DeProjekteSlugRoute
  AdminBlogPostsIndexRoute: typeof AdminBlogPostsIndexRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminTeamMembersIndexRoute: typeof AdminTeamMembersIndexRoute
  DeProjekteIndexRoute: typeof DeProjekteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/ueber': {
      id: '/de/ueber'
      path: '/de/ueber'
      fullPath: '/de/ueber'
      preLoaderRoute: typeof DeUeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/team': {
      id: '/de/team'
      path: '/de/team'
      fullPath: '/de/team'
      preLoaderRoute: typeof DeTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/spenden': {
      id: '/de/spenden'
      path: '/de/spenden'
      fullPath: '/de/spenden'
      preLoaderRoute: typeof DeSpendenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/kurse': {
      id: '/de/kurse'
      path: '/de/kurse'
      fullPath: '/de/kurse'
      preLoaderRoute: typeof DeKurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/kontakt': {
      id: '/de/kontakt'
      path: '/de/kontakt'
      fullPath: '/de/kontakt'
      preLoaderRoute: typeof DeKontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/projekte/': {
      id: '/de/projekte/'
      path: '/de/projekte'
      fullPath: '/de/projekte'
      preLoaderRoute: typeof DeProjekteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team-members/': {
      id: '/admin/team-members/'
      path: '/admin/team-members'
      fullPath: '/admin/team-members'
      preLoaderRoute: typeof AdminTeamMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog-posts/': {
      id: '/admin/blog-posts/'
      path: '/admin/blog-posts'
      fullPath: '/admin/blog-posts'
      preLoaderRoute: typeof AdminBlogPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/projekte/$slug': {
      id: '/de/projekte/$slug'
      path: '/de/projekte/$slug'
      fullPath: '/de/projekte/$slug'
      preLoaderRoute: typeof DeProjekteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team-members/$id': {
      id: '/admin/team-members/$id'
      path: '/admin/team-members/$id'
      fullPath: '/admin/team-members/$id'
      preLoaderRoute: typeof AdminTeamMembersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$id': {
      id: '/admin/projects/$id'
      path: '/admin/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages/$slug': {
      id: '/admin/pages/$slug'
      path: '/admin/pages/$slug'
      fullPath: '/admin/pages/$slug'
      preLoaderRoute: typeof AdminPagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/$id': {
      id: '/admin/courses/$id'
      path: '/admin/courses/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminCoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog-posts/$id': {
      id: '/admin/blog-posts/$id'
      path: '/admin/blog-posts/$id'
      fullPath: '/admin/blog-posts/$id'
      preLoaderRoute: typeof AdminBlogPostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DonateRoute: DonateRoute,
  ImprintRoute: ImprintRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TeamRoute: TeamRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DeKontaktRoute: DeKontaktRoute,
  DeKurseRoute: DeKurseRoute,
  DeSpendenRoute: DeSpendenRoute,
  DeTeamRoute: DeTeamRoute,
  DeUeberRoute: DeUeberRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  AdminBlogPostsIdRoute: AdminBlogPostsIdRoute,
  AdminCoursesIdRoute: AdminCoursesIdRoute,
  AdminPagesSlugRoute: AdminPagesSlugRoute,
  AdminProjectsIdRoute: AdminProjectsIdRoute,
  AdminTeamMembersIdRoute: AdminTeamMembersIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
  DeProjekteSlugRoute: DeProjekteSlugRoute,
  AdminBlogPostsIndexRoute: AdminBlogPostsIndexRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminTeamMembersIndexRoute: AdminTeamMembersIndexRoute,
  DeProjekteIndexRoute: DeProjekteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
